apps/options/urls.py
from django.urls import path

from .import views

app_name = 'options'


urlpatterns = [
    path('', views.index, name='index'),
]

custom_sites/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('options/', include('apps.options.urls', namespace='options')),
]

apps/options/models.py
from django.contrib.auth.models import Group
from django.db import models

# Create your models here.


class SiteConfiguration(models.Model):
    PADRAO = 'padrao'
    STYLE_CHOICES = [
        (PADRAO, 'Padrão'),
        ('cosmo', 'Cosmo'),
        ('flatly', 'Flatly'),
        ('litera', 'Litera'),
        ('lumen', 'Lumen'),
        ('materia', 'Materia'),
        ('sketchy', 'Sketchy'),
    ]

    name = models.CharField(max_length=10, primary_key=True)
    style = models.CharField(max_length=15, choices=STYLE_CHOICES, default=PADRAO)
    group = models.OneToOneField(
        Group, blank=False, related_query_name='site_configurations', unique=True, on_delete=models.PROTECT
    )
    created_date = models.DateTimeField(auto_now_add=True)

apps/options/forms.py
from django import forms

from apps.options.models import *


class SiteConfiguration(forms.ModelForm):
    class Meta:
        model = SiteConfiguration
        fields = ['name', 'style', 'group']
        labels = {
            'name': 'Nome',
            'style': 'Estilo',
            'group': 'Grupo',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'style': forms.Select(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }

apps/options/views.py
from django.shortcuts import render
from django.http import HttpResponse

from apps.options.forms import SiteConfiguration


def index(request):
    if request.method == 'POST':
        form = SiteConfiguration(request.POST)
    else:
        form = SiteConfiguration()

    return render(request, 'options/index.html', {'form': form})

templates/options/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-dark bg-dark box-shadow mb-4">
            <div class="container d-flex justify-content-between">
                <a class="navbar-brand" href="#">Navbar</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container" role="main">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Home</li>
            </ol>
        </nav>

        <h2>Modelo de Site</h2>

        <hr>

        <form action="{% url 'options:index' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <hr>

            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </main>


    <!-- JS -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>